const clients = [
    {
      id: 1,
      name: "John Smith",
      email: "john.smith@gmail.com",
      profilePic: "/images/john-smith.jpg",
      lifetimeValue: 12000,
      totalOrders: 22,
      phoneNumber: "+1 555-1234",
      membershipStatus: "Gold",
      location: "New York, USA",
      lastOrderDate: "2024-08-12"
    },
    {
      id: 2,
      name: "Emily Johnson",
      email: "emily.johnson@gmail.com",
      profilePic: "/images/emily-johnson.jpg",
      lifetimeValue: 8500,
      totalOrders: 15,
      phoneNumber: "+1 555-9876",
      membershipStatus: "Silver",
      location: "Los Angeles, USA",
      lastOrderDate: "2024-07-05"
    },
    {
      id: 3,
      name: "David Williams",
      email: "david.williams@gmail.com",
      profilePic: "/images/david-williams.jpg",
      lifetimeValue: 15000,
      totalOrders: 28,
      phoneNumber: "+1 555-5678",
      membershipStatus: "Platinum",
      location: "Chicago, USA",
      lastOrderDate: "2024-09-20"
    },
    {
      id: 4,
      name: "Olivia Brown",
      email: "olivia.brown@gmail.com",
      profilePic: "/images/olivia-brown.jpg",
      lifetimeValue: 9500,
      totalOrders: 18,
      phoneNumber: "+1 555-1122",
      membershipStatus: "Silver",
      location: "San Francisco, USA",
      lastOrderDate: "2024-08-30"
    },
    {
      id: 5,
      name: "Michael Davis",
      email: "michael.davis@gmail.com",
      profilePic: "/images/michael-davis.jpg",
      lifetimeValue: 17500,
      totalOrders: 34,
      phoneNumber: "+1 555-2233",
      membershipStatus: "Gold",
      location: "Houston, USA",
      lastOrderDate: "2024-07-19"
    },
    {
      id: 6,
      name: "Sophia Martinez",
      email: "sophia.martinez@gmail.com",
      profilePic: "/images/sophia-martinez.jpg",
      lifetimeValue: 21000,
      totalOrders: 40,
      phoneNumber: "+1 555-3344",
      membershipStatus: "Platinum",
      location: "Miami, USA",
      lastOrderDate: "2024-09-25"
    },
    {
      id: 7,
      name: "James Wilson",
      email: "james.wilson@gmail.com",
      profilePic: "/images/james-wilson.jpg",
      lifetimeValue: 8000,
      totalOrders: 16,
      phoneNumber: "+1 555-4455",
      membershipStatus: "Silver",
      location: "Phoenix, USA",
      lastOrderDate: "2024-08-15"
    },
    {
      id: 8,
      name: "Mia Thompson",
      email: "mia.thompson@gmail.com",
      profilePic: "/images/mia-thompson.jpg",
      lifetimeValue: 9000,
      totalOrders: 17,
      phoneNumber: "+1 555-5566",
      membershipStatus: "Gold",
      location: "Denver, USA",
      lastOrderDate: "2024-08-28"
    },
    {
      id: 9,
      name: "Ava Rodriguez",
      email: "ava.rodriguez@gmail.com",
      profilePic: "/images/ava-rodriguez.jpg",
      lifetimeValue: 7200,
      totalOrders: 13,
      phoneNumber: "+1 555-6677",
      membershipStatus: "Silver",
      location: "Atlanta, USA",
      lastOrderDate: "2024-08-10"
    },
    {
      id: 10,
      name: "Ethan Martinez",
      email: "ethan.martinez@gmail.com",
      profilePic: "/images/ethan-martinez.jpg",
      lifetimeValue: 11300,
      totalOrders: 21,
      phoneNumber: "+1 555-7788",
      membershipStatus: "Gold",
      location: "Seattle, USA",
      lastOrderDate: "2024-09-01"
    },
    {
      id: 11,
      name: "Harper White",
      email: "harper.white@gmail.com",
      profilePic: "/images/harper-white.jpg",
      lifetimeValue: 10400,
      totalOrders: 20,
      phoneNumber: "+1 555-8899",
      membershipStatus: "Silver",
      location: "Boston, USA",
      lastOrderDate: "2024-07-20"
    },
    {
      id: 12,
      name: "Lucas Lee",
      email: "lucas.lee@gmail.com",
      profilePic: "/images/lucas-lee.jpg",
      lifetimeValue: 13500,
      totalOrders: 25,
      phoneNumber: "+1 555-9900",
      membershipStatus: "Gold",
      location: "San Diego, USA",
      lastOrderDate: "2024-09-22"
    },
    {
      id: 13,
      name: "Ella Moore",
      email: "ella.moore@gmail.com",
      profilePic: "/images/ella-moore.jpg",
      lifetimeValue: 16500,
      totalOrders: 32,
      phoneNumber: "+1 555-1111",
      membershipStatus: "Platinum",
      location: "Dallas, USA",
      lastOrderDate: "2024-09-15"
    },
    {
      id: 14,
      name: "Aiden King",
      email: "aiden.king@gmail.com",
      profilePic: "/images/aiden-king.jpg",
      lifetimeValue: 14000,
      totalOrders: 26,
      phoneNumber: "+1 555-2222",
      membershipStatus: "Gold",
      location: "Austin, USA",
      lastOrderDate: "2024-09-05"
    },
    {
      id: 15,
      name: "Grace Green",
      email: "grace.green@gmail.com",
      profilePic: "/images/grace-green.jpg",
      lifetimeValue: 11000,
      totalOrders: 19,
      phoneNumber: "+1 555-3333",
      membershipStatus: "Silver",
      location: "Orlando, USA",
      lastOrderDate: "2024-08-18"
    },
    {
      id: 16,
      name: "Henry Hall",
      email: "henry.hall@gmail.com",
      profilePic: "/images/henry-hall.jpg",
      lifetimeValue: 13000,
      totalOrders: 24,
      phoneNumber: "+1 555-4444",
      membershipStatus: "Gold",
      location: "Portland, USA",
      lastOrderDate: "2024-09-07"
    },
    {
      id: 17,
      name: "Scarlett Young",
      email: "scarlett.young@gmail.com",
      profilePic: "/images/scarlett-young.jpg",
      lifetimeValue: 19000,
      totalOrders: 36,
      phoneNumber: "+1 555-5555",
      membershipStatus: "Platinum",
      location: "Charlotte, USA",
      lastOrderDate: "2024-09-16"
    },
    {
      id: 18,
      name: "Jack Anderson",
      email: "jack.anderson@gmail.com",
      profilePic: "/images/jack-anderson.jpg",
      lifetimeValue: 7500,
      totalOrders: 14,
      phoneNumber: "+1 555-6666",
      membershipStatus: "Silver",
      location: "Columbus, USA",
      lastOrderDate: "2024-07-28"
    },
    {
      id: 19,
      name: "Lily Thomas",
      email: "lily.thomas@gmail.com",
      profilePic: "/images/lily-thomas.jpg",
      lifetimeValue: 9200,
      totalOrders: 17,
      phoneNumber: "+1 555-7777",
      membershipStatus: "Gold",
      location: "Indianapolis, USA",
      lastOrderDate: "2024-08-02"
    },
    {
      id: 20,
      name: "Daniel Harris",
      email: "daniel.harris@gmail.com",
      profilePic: "/images/daniel-harris.jpg",
      lifetimeValue: 12500,
      totalOrders: 23,
      phoneNumber: "+1 555-8888",
      membershipStatus: "Gold",
      location: "Nashville, USA",
      lastOrderDate: "2024-08-21"
    },
    {
      id: 21,
      name: "Zoe Clark",
      email: "zoe.clark@gmail.com",
      profilePic: "/images/zoe-clark.jpg",
      lifetimeValue: 10200,
      totalOrders: 19,
      phoneNumber: "+1 555-9999",
      membershipStatus: "Silver",
      location: "Phoenix, USA",
      lastOrderDate: "2024-08-15"
    },
    {
      id: 22,
      name: "Liam Walker",
      email: "liam.walker@gmail.com",
      profilePic: "/images/liam-walker.jpg",
      lifetimeValue: 18500,
      totalOrders: 34,
      phoneNumber: "+1 555-0000",
      membershipStatus: "Platinum",
      location: "Tampa, USA",
      lastOrderDate: "2024-09-10"
    },
    {
      id: 23,
      name: "Charlotte Lewis",
      email: "charlotte.lewis@gmail.com",
      profilePic: "/images/charlotte-lewis.jpg",
      lifetimeValue: 8600,
      totalOrders: 16,
      phoneNumber: "+1 555-1112",
      membershipStatus: "Silver",
      location: "Las Vegas, USA",
      lastOrderDate: "2024-09-05"
    },
    {
      id: 24,
      name: "Noah Scott",
      email: "noah.scott@gmail.com",
      profilePic: "/images/noah-scott.jpg",
      lifetimeValue: 17400,
      totalOrders: 30,
      phoneNumber: "+1 555-1212",
      membershipStatus: "Gold",
      location: "Philadelphia, USA",
      lastOrderDate: "2024-09-12"
    },
    {
      id: 25,
      name: "Amelia Adams",
      email: "amelia.adams@gmail.com",
      profilePic: "/images/amelia-adams.jpg",
      lifetimeValue: 20000,
      totalOrders: 39,
      phoneNumber: "+1 555-1313",
      membershipStatus: "Platinum",
      location: "Minneapolis, USA",
      lastOrderDate: "2024-09-25"
    }
  ];

  export {clients};